type Query {
  """ Get all users """
  users(query: String): [User!]!
  me: User!
}
type User {
  id: ID!
  """ Nama lengkap """
  name: String!
  email: String!
  gender: Gender
}

enum Gender {
  MALE
  FEMALE
}

type Mutation {
  createUser(data: CreateUserInput!): User!
  deleteUser(id: ID!): User!
}

input CreateUserInput {
  name: String!
  email: String!
  age: Int
}
